datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: victoriametrics
      type: prometheus
      orgId: 1
      url: http://victoria-metrics-single-server.monitoring.svc.cluster.local:8428
      access: proxy
      isDefault: true
      updateIntervalSeconds: 10
      editable: true