apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: otel-nest-dice
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
        project: default
        source:
            repoURL: https://github.com/khantnaingset-kns/otel-nest-dice
            targetRevision: main
            helm:
                releaseName: otel-nest-dice
        destination:
            server: https://kubernetes.default.svc
            namespace: default
        syncPolicy:
            automated:
                prune: true
                selfHeal: true
